# Site settings
title: Civica Digital
email: hola@civica.digital
description: > # this means to ignore newlines until "baseurl:"
  Desarrollamos tecnología que empodera a los ciudadanos, junto con ellos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://civica.digital" # the base hostname & protocol for your sites
github_username:  civica-digital
twitter: "@civicadigital"

analytics: UA-XXXXX-X

langs:
  - en
  - es

# Build settings
markdown: kramdown
exclude: [vendor]
