# Site settings
title: Civica Digital
email: info@civica.digital
description: > # this means to ignore newlines until "baseurl:"
  Frase super inspiradora de la visión y/o misión de Cívica Digital.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://civica.digital" # the base hostname & protocol for your sites
github_username:  civica-digital

# Build settings
markdown: kramdown
