title: Servicios

section:
  - meta:
      icon: icon-desarrollo
    title: Apps Cívicas
    desc: "Desarrollamos soluciones tecnológicas para generar impacto en el ámbito social y público, a través de: "
    list:
      - title:  Web apps
        desc: Desde la nube para múltiples dispositivos, websites que funcionan como plataforma.
      - title: Móviles
        desc: Aplicaciones iOS / Android simples que generen confianza.
      - title: Productos
        desc: Te ayudamos a implementar una de nuestras aplicaciones open source en tu comunidad.

  - meta:
      icon: icon-consultoria
    title: Datos Abiertos
    desc: "Asociaciones Civiles Empresas o Gobiernos. Te acompañamos durante todo el proceso, desde entender qué son, hasta qué se puede hacer con ellos."
    list:
      - title: Procesos de apertura
        desc: Saber por dónde empezar para abrir datos puede ser un reto. Con nuestra metodología basada en mejores prácticas, establecer esta ruta en tu organización será mucho menos complicado.
      - title: Plataformas & APIs
        desc: Podemos ayudarte a decidir e implementar cómo abrirás tus datos.
      - title: Entrenamientos
        desc: Construye capacidades dentro de tu equipo u organización.

  - meta:
      icon: icon-educacion
    title: Innovación Abierta
    desc: Genera participación alrededor de tus datos y problemáticas, los retos de tu organización no siempre se resuelven sólo desde adentro.
    list:
      - title: Acompañamiento
        desc: A través de un proceso abierto, te acompañamos para abrir tus retos a la participación de la comunidad.

      - title: Entrenamiento
        desc: Nadie conoce como tú las problemáticas de tu organización. Podemos entrenarte para que utilizar el modelo de innovación abierta se vuelva algo común en tu equipo.
